lan_kommun = {
"Dalarnas län":["Avesta kommun","Borlänge kommun","Falu kommun","Gagnefs kommun","Hedemora kommun","Leksands kommun","Ludvika kommun","Malung-Sälens kommun","Mora kommun","Orsa kommun","Rättviks kommun","Smedjebackens kommun","Säters kommun","Vansbro kommun","Älvdalens kommun"],
"Jämtlands län":["Bergs kommun","Bräcke kommun","Härjedalens kommun","Krokoms kommun","Ragunda kommun","Strömsunds kommun","Åre kommun","Östersunds kommun"],
"Skåne län":["Bjuvs kommun","Bromölla kommun","Burlövs kommun","Båstads kommun","Eslövs kommun","Helsingborgs kommun","Hässleholms kommun","Höganäs kommun","Hörby kommun","Höörs kommun","Klippans kommun","Kristianstads kommun","Kävlinge kommun","Landskrona kommun","Lomma kommun","Lunds kommun","Malmö kommun","Osby kommun","Perstorps kommun","Simrishamns kommun","Sjöbo kommun","Skurups kommun","Staffanstorps kommun","Svalövs kommun","Svedala kommun","Tomelilla kommun","Trelleborgs kommun","Vellinge kommun","Ystads kommun","Åstorps kommun","Ängelholms kommun","Örkelljunga kommun","Östra Göinge kommun"],
"Värmlands län":["Arvika kommun","Eda kommun","Filipstads kommun","Forshaga kommun","Grums kommun","Hagfors kommun","Hammarö kommun","Karlstads kommun","Kils kommun","Kristinehamns kommun","Munkfors kommun","Storfors kommun","Sunne kommun","Säffle kommun","Torsby kommun","Årjängs kommun"],
"Västernorrlands län":["Härnösands kommun","Kramfors kommun","Sollefteå kommun","Sundsvalls kommun","Timrå kommun","Ånge kommun","Örnsköldsviks kommun"],
"Östergötlands län":["Boxholms kommun","Finspångs kommun","Kinda kommun","Linköpings kommun","Mjölby kommun","Motala kommun","Norrköpings kommun","Söderköpings kommun","Vadstena kommun","Valdemarsviks kommun","Ydre kommun","Åtvidabergs kommun","Ödeshögs kommun"],
"Jönköpings län":["Aneby kommun","Eksjö kommun","Gislaveds kommun","Gnosjö kommun","Habo kommun","Jönköpings kommun","Mullsjö kommun","Nässjö kommun","Sävsjö kommun","Tranås kommun","Vaggeryds kommun","Vetlanda kommun","Värnamo kommun"],
"Hallands län":["Falkenbergs kommun","Halmstads kommun","Hylte kommun","Kungsbacka kommun","Laholms kommun","Varbergs kommun"],
"Kalmars län":["Borgholms kommun","Emmaboda kommun","Hultsfreds kommun","Högsby kommun","Kalmar kommun","Mönsterås kommun","Mörbylånga kommun","Nybro kommun","Oskarshamns kommun","Torsås kommun","Vimmerby kommun","Västerviks kommun"],
"Västerbottens län":["Bjurholms kommun","Dorotea kommun","Lycksele kommun","Malå kommun","Nordmalings kommun","Norsjö kommun","Robertsfors kommun","Skellefteå kommun","Sorsele kommun","Storumans kommun","Umeå kommun","Vilhelmina kommun","Vindelns kommun","Vännäs kommun","Åsele kommun"],
"Norrbottens län":["Arjeplogs kommun","Arvidsjaurs kommun","Bodens kommun","Gällivare kommun","Haparanda kommun","Jokkmokks kommun","Kalix kommun","Kiruna kommun","Luleå kommun","Pajala kommun","Piteå kommun","Älvsbyns kommun","Överkalix kommun","Övertorneå kommun"],
"Södermanlands län":["Eskilstuna kommun","Flens kommun","Gnesta kommun","Katrineholms kommun","Nyköpings kommun","Oxelösunds kommun","Strängnäs kommun","Trosa kommun","Vingåkers kommun"],
"Gävleborgs län":["Bollnäs kommun","Gävle kommun","Hofors kommun","Hudiksvalls kommun","Ljusdals kommun","Nordanstigs kommun","Ockelbo kommun","Ovanåkers kommun","Sandvikens kommun","Söderhamns kommun"],
"Gotlands län":["Gotlands kommun"],
"Kronobergs län":["Alvesta kommun","Lessebo kommun","Ljungby kommun","Markaryds kommun","Tingsryds kommun","Uppvidinge kommun","Växjö kommun","Älmhults kommun"],
"Blekinge län":["Karlshamns kommun","Karlskrona kommun","Olofströms kommun","Ronneby kommun","Sölvesborgs kommun"],
"Stockholms län":["Botkyrka kommun","Danderyds kommun","Ekerö kommun","Haninge kommun","Huddinge kommun","Järfälla kommun","Lidingö kommun","Nacka kommun","Norrtälje kommun","Nykvarns kommun","Nynäshamns kommun","Salems kommun","Sigtuna kommun","Sollentuna kommun","Solna kommun","Stockholms kommun","Sundbybergs kommun","Södertälje kommun","Tyresö kommun","Täby kommun","Upplands Väsby kommun","Upplands-Bro kommun","Vallentuna kommun","Vaxholms kommun","Värmdö kommun","Österåkers kommun"],
"Uppsala län":["Enköpings kommun","Heby kommun","Håbo kommun","Knivsta kommun","Tierps kommun","Uppsala kommun","Älvkarleby kommun","Östhammars kommun"],
"Västmanlands län":["Arboga kommun","Fagersta kommun","Hallstahammars kommun","Kungsörs kommun","Köpings kommun","Norbergs kommun","Sala kommun","Skinnskattebergs kommun","Surahammars kommun","Västerås kommun"],
"Västras Götalands län":["Ale kommun","Alingsås kommun","Bengtsfors kommun","Bollebygds kommun","Borås kommun","Dals-Eds kommun","Essunga kommun","Falköpings kommun","Färgelanda kommun","Grästorps kommun","Gullspångs kommun","Göteborgs kommun","Götene kommun","Herrljunga kommun","Hjo kommun","Härryda kommun","Karlsborgs kommun","Kungälvs kommun","Lerums kommun","Lidköpings kommun","Lilla Edets kommun","Lysekils kommun","Mariestads kommun","Marks kommun","Melleruds kommun","Munkedals kommun","Mölndals kommun","Orusts kommun","Partille kommun","Skara kommun","Skövde kommun","Sotenäs kommun","Stenungsunds kommun","Strömstads kommun","Svenljunga kommun","Tanums kommun","Tibro kommun","Tidaholms kommun","Tjörns kommun","Tranemo kommun","Trollhättans kommun","Töreboda kommun","Uddevalla kommun","Ulricehamns kommun","Vara kommun","Vårgårda kommun","Vänersborgs kommun","Åmåls kommun","Öckerö kommun"],
"Örebro län":["Askersunds kommun","Degerfors kommun","Hallsbergs kommun","Hällefors kommun","Karlskoga kommun","Kumla kommun","Laxå kommun","Lekebergs kommun","Lindesbergs kommun","Ljusnarsbergs kommun","Nora kommun","Örebro kommun"]
}

kommun_tatort = {
"Upplands Väsby kommun":["Löwenströmska lasarettet"],
"Årjängs kommun":["Töcksfors","Årjäng"],
"Stenungsunds kommun":["Jörlanda","Spekeröd","Stenungsund","Stenungsön","Stora Höga","Svartehallen","Svenshögen","Ucklum","Ödsmål"],
"Nordanstigs kommun":["Bergsjö","Gnarp","Harmånger","Hassela","Ilsbo","Jättendal","Stocka","Strömsbruk"],
"Halmstads kommun":["Eldsberga","Frösakull","Getinge","Gullbrandstorp","Gullbranna","Halmstad","Harplinge","Haverdal","Holm","Kvibille","Laxvik","Oskarström","Sennan","Simlångsdalen","Skedala","Steninge","Trönninge","Villshärad","Åled"],
"Östersunds kommun":["Fåker","Hara","Häggenås","Lit","Lunne","Marieby","Målsta","Orrviken","Tandsbyn","Ängsmon","Östersund"],
"Essunga kommun":["Främmestad","Jonslund","Nossebro"],
"Arvidsjaurs kommun":["Arvidsjaur","Glommersträsk"],
"Hagfors kommun":["Bergsäng","Ekshärad","Hagfors","Mjönäs","Råda","Sunnemo","Uddeholm"],
"Kristinehamns kommun":["Björneborg","Bäckhammar","Kristinehamn","Ölme"],
"Mörbylånga kommun":["Algutsrum","Degerhamn","Färjestaden","Glömminge","Gårdby","Kastlösa","Mörbylånga","Saxnäs","Skogsby","Vickleby"],
"Tranås kommun":["Gripenberg","Hätte, Seglarvik och Sandvik","Sommen","Tranås"],
"Heby kommun":["Harbo","Heby","Morgongåva","Tärnsjö","Vittinge","Östervåla"],
"Sala kommun":["Möklinta","Ransta","Sala","Salbohed","Sätra Brunn","Västerfärnebo"],
"Mönsterås kommun":["Blomstermåla","Fliseryd","Mönsterås","Oknö","Timmernabben"],
"Sollentuna kommun":["Upplands Väsby och Sollentuna"],
"Vilhelmina kommun":["Vilhelmina"],
"Tomelilla kommun":["Brösarp","Lunnarp","Onslunda","Skåne-Tranås","Smedstorp","Spjutstorp","Tomelilla"],
"Simrishamns kommun":["Baskemölla","Borrby","Brantevik","Gärsnäs","Hammenhög","Kivik","Sankt Olof","Simrishamn","Skillinge","Vik","Vitaby","Östra Tommarp","Östra Vemmerlöv"],
"Eskilstuna kommun":["Alberga","Bälgviken","Eskilstuna","Hållsta","Hällberga","Hällbybrunn","Kjulaås","Kullersta","Skiftinge","Sundbyholm","Torshälla","Tumbo","Udden","Ärla"],
"Mora kommun":["Bonäs","Gesunda","Mora","Nusnäs","Selja","Sollerön","Stenis","Vattnäs","Venjan","Vinäs","Våmhus"],
"Osby kommun":["Killeberg","Lönsboda","Osby"],
"Höörs kommun":["Höör","Norra Rörum","Sjunnerup","Snogeröd","Tjörnarp"],
"Ockelbo kommun":["Lingbo","Ockelbo","Åmot"],
"Sundsvalls kommun":["Ankarsvik","Fanbyn","Hartungviken och Spikarna","Hovid","Indal","Klingsta och Allsta","Kovland","Kvissleby","Liden","Lucksta","Matfors","Nedansjö","Selånger","Stockvik","Stöde","Sundsvall","Vattjom","Vi","Viforsen och Tunbyn","Vikarbodarna och Skatan"],
"Falu kommun":["Aspeboda","Bengtsheden","Bjursås","Blixbo","Danholn","Enviken","Falun","Gamla Berget och Korsgården","Grycksbo","Linghed","Stennäset","Sundborn","Svärdsjö","Sågmyra","Toftbyn","Vika","Övertänger"],
"Gnosjö kommun":["Gnosjö","Hillerstorp","Kulltorp","Nissafors","Törestorp"],
"Söderköpings kommun":["Luddingsbo","Mogata","Snöveltorp","Söderköping","Västra Husby","Östra Ryd"],
"Hallstahammars kommun":["Hallstahammar","Kolbäck","Strömsholm","Sörstafors"],
"Finspångs kommun":["Borggård","Butbro","Falla","Finspång","Grytgöl","Hällestad","Igelfors","Ljusfallshammar","Lotorp","Rejmyre","Sonstorp"],
"Köpings kommun":["Kolsva","Köping","Munktorp"],
"Södertälje kommun":["Ekeby","Hölö","Järna","Kallfors","Mölnbo","Nibble","Pershagen","Sandviken","Södertälje","Tuna","Vattubrinken","Viksäter och Viksberg","Östra Kallfors"],
"Nybro kommun":["Alsterbro","Bäckebo","Flerohopp","Flygsfors","Kristvallabrunn","Nybro","Orrefors","Örsjö"],
"Vimmerby kommun":["Frödinge","Gullringen","Storebro","Södra Vi","Tuna","Vimmerby"],
"Växjö kommun":["Braås","Furuby","Gemla","Ingelstad","Lammhult","Nöbbele","Rottne","Tävelsås","Växjö","Åby","Åryd"],
"Götene kommun":["Götene","Hällekis","Källby","Lundsbrunn"],
"Tingsryds kommun":["Konga","Linneryd","Ryd","Rävemåla","Tingsryd","Urshult","Väckelsång"],
"Säffle kommun":["Svanskog/Svaneholm","Säffle","Värmlandsbro"],
"Karlskoga kommun":["Karlskoga","Valåsen och Labbsand"],
"Varbergs kommun":["Bua","Getterön","Himle","Hunnestad","Kungsäter","Nordvära och Källstorp","Rolfstorp","Skällinge","Tofta","Torpa","Trönningenäs","Tvååker","Tångaberg","Valinge","Varberg","Veddige","Väröbacka","Årnäs","Åsby"],
"Leksands kommun":["Alvik","Djura","Hjortnäs","Häradsbygden","Insjön","Leksand","Siljansnäs","Tällberg","Västanvik"],
"Malmö kommun":["Bunkeflostrand","Malmö","Oxie","Skumparp","Tygelsjö","Vintrie"],
"Gullspångs kommun":["Gullspång","Hova","Otterbäcken"],
"Pajala kommun":["Junosuando","Kangos","Korpilombolo","Pajala"],
"Skellefteå kommun":["Boliden","Bureå","Burträsk","Bygdsiljum","Byske","Drängsmark","Ersmark","Jörn","Klutmark","Kusmark","Kåge","Lövånger","Medle","Myckle","Ostvik","Skelleftehamn","Skellefteå","Södra Bergsbyn och Stackgrönnan","Ursviken","Örviken"],
"Karlsborgs kommun":["Forsvik","Karlsborg","Mölltorp","Undenäs"],
"Haninge kommun":["Dalarö","Jordbro","Muskö","Norra Muskö","Söderby","Väländan","Västerhaninge","Årsta Havsbad"],
"Mullsjö kommun":["Mullsjö","Sandhem"],
"Arboga kommun":["Arboga","Götlunda","Medåker"],
"Bjurholms kommun":["Bjurholm"],
"Degerfors kommun":["Degerfors","Svartå"],
"Svenljunga kommun":["Hillared","Holsljunga","Mjöbäck","Sexdrega","Svenljunga","Östra Frölunda","Överlida"],
"Älvsbyns kommun":["Korsträsk","Vidsel","Vistträsk","Älvsbyn"],
"Skinnskattebergs kommun":["Riddarhyttan","Skinnskatteberg"],
"Ekerö kommun":["Drottningholm","Ekerö","Ekerö sommarstad","Hilleshögby","Kungsberga","Lilla Stenby","Lurudden","Parksidan","Stenhamra","Sundby","Söderby","Tureholm","Älvnäs","Ölsta"],
"Kinda kommun":["Horn","Kisa","Rimforsa"],
"Vännäs kommun":["Vännäs","Vännäsby"],
"Örnsköldsviks kommun":["Billsta","Bjästa","Björna","Bredbyn","Gideå","Gottne","Husum","Köpmanholmen","Långviksmon","Mellansel","Moliden","Sidensjö","Åmynnet","Örnsköldsvik"],
"Robertsfors kommun":["Bygdeå","Robertsfors","Ånäset"],
"Nykvarns kommun":["Finkarby","Nykvarn","Stensättra tomtområde"],
"Österåkers kommun":["Bammarboda","Laggarsvik och Linanäs","Ljusterö Nolsjö","Nyhagen och Översättra","Rydbo","Solberga","Spånlöt","Stava","Svinninge","Täljö","Åkersberga"],
"Umeå kommun":["Botsmark","Brännland","Brännäset och Boviken","Bullmark","Ersmark","Flurkmark","Hissjö","Holmsund","Hörnefors","Innertavle","Norrmjöle","Obbola","Röbäck","Stöcke","Stöcksjö","Sävar","Sörfors","Sörmjöle","Tavelsjö","Tomtebo","Täfteå","Umeå","Yttersjö","Överboda"],
"Bodens kommun":["Boden","Harads","Sävast","Södra Bredåker","Trångforsen och Heden","Unbyn","Vittjärv"],
"Arjeplogs kommun":["Arjeplog"],
"Ystads kommun":["Glemmingebro","Hedeskoga","Köpingebro","Löderup","Nybrostrand","Rynge och Vallösa","Stora Herrestad","Svarte","Sövestad","Ystad"],
"Haparanda kommun":["Haparanda","Karungi","Nikkala","Seskarö"],
"Vetlanda kommun":["Björköby","Ekenässjön","Holsbybrunn","Korsberga","Kvillsfors","Landsbro","Myresjö","Nye","Pauliström","Sjunnen","Skede","Vetlanda"],
"Hylte kommun":["Hyltebruk","Kinnared","Landeryd","Rydöbruk","Torup","Unnaryd"],
"Ånge kommun":["Alby","Fränsta","Torpshammar","Ånge"],
"Stockholms kommun":["Stockholm"],
"Nyköpings kommun":["Arnö","Bergshammar","Buskhyttan","Enstaberga","Jönåker","Kvegerö","Nyköping","Nävekvarn","Runtuna","Sjösa","Skeppsvik","Stavsjö","Stigtomta","Svalsta","Tystberga","Vrena","Ålberga"],
"Ale kommun":["Alvhem","Nödinge-Nol","Skepplanda","Surte","Älvängen"],
"Melleruds kommun":["Dals Rostock","Mellerud","Åsensbruk"],
"Tranemo kommun":["Ambjörnarp","Dalstorp","Grimsås","Limmared","Ljungsarp","Länghem","Rosenlund","Tranemo","Uddebo"],
"Åmåls kommun":["Fengersfors","Tösse","Åmål"],
"Bromölla kommun":["Bromölla","Gualöv","Nymölla","Näsum","Valje"],
"Grums kommun":["Grums","Segmon","Slottsbron"],
"Lilla Edets kommun":["Göta","Hjärtum","Lilla Edet","Lilla Edet västra","Lödöse","Nygård"],
"Sävsjö kommun":["Rörvik","Stockaryd","Sävsjö","Vrigstad"],
"Lysekils kommun":["Brastad","Fiskebäckskil","Grundsund","Lysekil"],
"Fagersta kommun":["Fagersta","Hedkärra"],
"Örebro kommun":["Askersby","Ekeby-Almby","Garphyttan","Glanshammar","Hampetorp","Hovsta","Kilsmo","Latorpsbruk","Norra Bro","Odensbacken","Stora Mellösa","Ölmbrotorp","Örebro"],
"Strängnäs kommun":["Abborrberget","Björktorp och Sanda","Husby och Tuna","Härad","Kalkudden","Mariefred","Marielund","Merlänna","Stallarholmen","Strängnäs","Vansö kyrkby","Åkers styckebruk"],
"Söderhamns kommun":["Bergvik","Ljusne","Marmaskogen","Mohed","Sandarne","Söderhamn","Trönö","Vad, Åsbacka och Långrör","Vallvik","Vannsätter"],
"Älvdalens kommun":["Brunnsberg","Evertsberg","Idre","Rot","Särna","Västermyckeläng","Älvdalen"],
"Älmhults kommun":["Diö","Eneryda","Liatorp","Älmhult"],
"Herrljunga kommun":["Herrljunga","Ljung och Annelund"],
"Borlänge kommun":["Borlänge","Halvarsgårdarna","Idkerberget","Norr Amsberg","Ornäs","Repbäcken","Romme","Torsång"],
"Åtvidabergs kommun":["Berg","Björsäter","Falerum","Grebo","Åtvidaberg"],
"Hedemora kommun":["Garpenberg","Hedemora","Långshyttan","Vikmanshyttan","Västerby"],
"Vallentuna kommun":["Brottby","Ekskogen","Ekskogen, Älgeby och Långsjötorp","Johannesudd","Karby","Kårsta","Lindholmen","Vallentuna"],
"Gislaveds kommun":["Anderstorp","Broaryd","Burseryd","Gislaved","Hestra","Reftele","Skeppshult","Smålandsstenar"],
"Arvika kommun":["Arvika","Edane","Glava","Gunnarskog","Jössefors","Klässbol","Prästängen","Sulvik"],
"Åstorps kommun":["Björnås","Hyllinge","Kvidinge","Åstorp"],
"Sigtuna kommun":["Granby","Märsta","Rosersberg","Sigtuna","Steningehöjden"],
"Övertorneå kommun":["Hedenäset","Juoksengi","Övertorneå"],
"Perstorps kommun":["Perstorp"],
"Botkyrka kommun":["Norra Riksten","Sibble","Tumba","Vårsta"],
"Värmdö kommun":["Baldersnäs","Betsede","Brunn","Djurö","Fågelvikshöjden","Gustavsberg","Kopparmora","Koviksudde och Skeviksstrand","Lugnet och Skälsmara","Långvik","Norra Ingaröstrand och Skälsmara","Norra Lagnö","Norra Vindö","Stavsnäs","Strömma","Älvsala","Ängsvik"],
"Ängelholms kommun":["Hjärnarp","Lerbäckshult","Margretetorp","Munka-Ljungby","Strövelstorp","Svenstorp","Toarp och Tåstarp","Ängelholm","Ängelholms strand","Össjö"],
"Gävle kommun":["Berg","Bergby","Björke","Bönan","Forsbacka","Furuvik","Gävle","Harkskär och Utvalnäs","Hedesunda","Källhagen","Norrsundet","Sälgsjön","Trödje","Valbo","Åbyggeby","Överhärde"],
"Gotlands kommun":["Burgsvik","Fårösund","Havdhem","Hemse","Klintehamn","Lärbro","Norra Visby","Romakloster","Själsö","Slite","Slite norra","Stånga","Tingstäde","Tofta","Vibble","Visby","Väskinde","Västerhejde"],
"Hudiksvalls kommun":["Delsbo","Edsta","Enånger","Fredriksfors","Friggesund","Hudiksvall","Iggesund","Njutånger","Näsviken","Sörforsa"],
"Ödeshögs kommun":["Hästholmen","Ödeshög"],
"Ulricehamns kommun":["Blidsberg","Dalum","Gällstad","Hulu","Hökerum","Marbäck","Nitta","Rånnaväg","Timmele","Trädet","Ulricehamn","Vegby"],
"Högsby kommun":["Berga","Fagerhult","Fågelfors","Högsby","Ruda"],
"Hallsbergs kommun":["Hallsberg","Hjortkvarn","Pålsboda","Sköllersta","Vretstorp","Östansjö"],
"Gagnefs kommun":["Björbo","Bäsna","Djurås","Dala-Floda","Gagnef","Mockfjärd","Sifferbo"],
"Klippans kommun":["Klippan","Klippans bruk","Krika","Ljungbyhed","Östra Ljungby"],
"Lycksele kommun":["Hedlunda","Lycksele","Rusksele"],
"Nässjö kommun":["Anneberg","Bodafors","Forserum","Fredriksdal","Grimstorp","Malmbäck","Nässjö","Ormaryd","Solberga","Stensjön","Äng"],
"Norrtälje kommun":["Bergshamra","Blidö","Edsbro","Finsta","Grisslehamn","Gräddö","Hallstavik","Herräng","Hästängen","Norrtälje","Nysättra","Riala","Rimbo","Rånäs","Skebobruk","Spillersboda","Svanberga","Sättra","Söderby-Karl","Södersvik","Älmsta"],
"Lunds kommun":["Dalby","Genarp","Lund","Revingeby","Stångby","Södra Sandby","Torna Hällestad","Vallkärra","Veberöd"],
"Hällefors kommun":["Grythyttan","Hällefors"],
"Ljusnarsbergs kommun":["Kopparberg","Ställdalen"],
"Höganäs kommun":["Arild","Farhult","Höganäs","Ingelsträde","Jonstorp","Mjöhult","Mölle","Viken"],
"Smedjebackens kommun":["Gubbo","Hagge","Smedjebacken","Söderbärke","Vad"],
"Lomma kommun":["Bjärred","Flädie","Lomma"],
"Torsås kommun":["Bergkvara","Söderåkra","Torsås"],
"Katrineholms kommun":["Bie","Björkvik","Forssjö","Katrineholm","Sköldinge","Strångsjö","Valla","Äsköping"],
"Härjedalens kommun":["Funäsdalen","Hede","Lillhärdal","Norr-Hede","Sveg","Ulvkälla","Vemdalen","Ytterhogdal"],
"Färgelanda kommun":["Färgelanda","Högsäter","Stigen","Ödeborg"],
"Eksjö kommun":["Bruzaholm","Eksjö","Hjältevad","Hult","Ingatorp","Mariannelund"],
"Olofströms kommun":["Gränum","Jämshög","Kyrkhult","Olofström","Vilshult"],
"Orsa kommun":["Orsa","Skattungbyn"],
"Åre kommun":["Björnänge","Hallen","Järpen","Mörsil","Undersåker","Åre"],
"Upplands-Bro kommun":["Bro","Brunna","Håbo-Tibble kyrkby","Kungsängen","Rättarboda"],
"Hultsfreds kommun":["Hultsfred","Järnforsen","Målilla","Mörlunda","Rosenfors","Silverdalen","Vena","Virserum"],
"Åsele kommun":["Åsele"],
"Vansbro kommun":["Heden och Skansbacken","Järna","Nås","Skålö","Vansbro","Äppelbo"],
"Grästorps kommun":["Grästorp"],
"Älvkarleby kommun":["Gårdskär","Marma","Skutskär","Älvkarleby","Älvkarleö"],
"Flens kommun":["Bettna","Flen","Hälleforsnäs","Malmköping","Mellösa","Orrhammar","Skebokvarn","Sparreholm"],
"Enköpings kommun":["Bredsand","Enköping","Fjärdhundra","Grillby","Haga","Hummelsta","Lillkyrka","Örsundsbro","Örsundsbro norra"],
"Burlövs kommun":["Burlövs egnahem","Åkarp"],
"Emmaboda kommun":["Emmaboda","Eriksmåla","Johansfors","Långasjö","Vissefjärda"],
"Ronneby kommun":["Backaryd","Bräkne-Hoby","Bökenäs, Korsanäs och Kuggeboda","Eringsboda","Hallabro","Johannishus","Kallinge","Listerby","Ronneby","Ronnebyhamn","Spjälkö och Saxemara"],
"Sjöbo kommun":["Bjärsjölagård","Blentarp","Karups sommarby","Lövestad","Sjöbo","Sövde","Vollsjö","Äsperöd"],
"Ragunda kommun":["Hammarstrand","Stugun","Västra Bispgården","Östra Bispgården"],
"Storfors kommun":["Kyrksten","Storfors"],
"Vänersborgs kommun":["Brålanda","Frändefors","Katrinedal","Nordkroken","Vargön","Vänersborg"],
"Sorsele kommun":["Sorsele"],
"Sunne kommun":["Lysvik","Rottneros","Sunne","Uddheden","Västra Ämtervik"],
"Täby kommun":["Arninge"],
"Sölvesborgs kommun":["Djupekås","Hällevik","Hörvik","Lörby","Mjällby","Norje","Pukavik","Sölvesborg","Ysane"],
"Sandvikens kommun":["Hammarby","Hillsta och Se","Jäderfors","Järbo","Kungsgården","Sandviken","Storvik","Västerberg","Årsunda","Åshammar","Österfärnebo"],
"Trelleborgs kommun":["Alstad","Anderslöv","Beddingestrand","Klagstorp","Kurland","Skegrie","Smygehamn","Trelleborg","Västra Tommarp"],
"Linköpings kommun":["Askeby","Bankekind","Berg","Bestorp","Brokind","Ekängen","Gistad","Kränge","Linghem","Linköping","Ljungsbro","Malmslätt","Nykil","Rappestad","Sjögestad","Skeda udde","Slaka","Sturefors","Tallboda","Ulrika","Vikingstad","Västerlösa"],
"Eda kommun":["Charlottenberg","Eda Glasbruk","Koppom","Åmotfors"],
"Luleå kommun":["Alvik","Antnäs","Avan","Bensbyn","Bergnäset","Björkskatan","Brändön","Bälinge","Ersnäs","Gammelstaden","Hällbäcken och Sinksundet","Jämtön","Kallax","Karlsvik","Klöverträsk","Luleå","Måttsund","Persön","Rutvik","Råneå","Sundom","Södra Sunderbyn","Ängesbyn Skaulo"],
"Munkfors kommun":["Munkfors"],
"Skara kommun":["Ardala","Axvall","Eggby","Skara","Varnhem"],
"Sotenäs kommun":["Bovallstrand","Hunnebostrand","Kungshamn","Malmön","Smögen"],
"Ovanåkers kommun":["Alfta","Edsbyn","Roteberg","Runemo","Viksjöfors"],
"Östra Göinge kommun":["Broby","Glimåkra","Hanaskog","Hjärsås","Immeln","Knislinge","Sibbhult"],
"Staffanstorps kommun":["Bergströmshusen","Hjärup","Kyrkheddinge","Staffanstorp"],
"Bergs kommun":["Hackås","Hoverberg","Klövsjö","Myrviken","Rätan","Svenstavik","Åsarna"],
"Mjölby kommun":["Hogstad","Mantorp","Mjölby","Skänninge","Spångsholm","Sya","Väderstad"],
"Hammarö kommun":["Rud","Skoghall","Tye","Vidöåsen"],
"Kävlinge kommun":["Barsebäck","Barsebäckshamn","Dösjebro","Furulund","Hofterup","Järavallen","Kävlinge","Lilla Harrie","Löddeköpinge","Sandskogen","Västra Karaby"],
"Västerås kommun":["Barkarö","Dingtuna","Enhagen-Ekbacken","Harkie","Hökåsen","Irsta","Kvicksund","Kärsta","Lycksta","Malmen","Munga","Skultuna","Tidö-Lindö","Tillberga","Tortuna","Västerås","Örtagården"],
"Ljungby kommun":["Angelstad","Kånna","Lagan","Lidhult","Ljungby","Ryssby","Vittaryd"],
"Partille kommun":["Jonsered","Kåhög","Öjersjö"],
"Marks kommun":["Berghem","Björketorp","Fritsla","Horred","Hyssna","Kinna","Rydal","Sätila","Torestorp","Ubbhult norra","Öxabäck"],
"Överkalix kommun":["Svartbyn","Tallvik","Överkalix"],
"Håbo kommun":["Bålsta","Häggeby och Vreta","Krägga","Råby","Skörby","Slottsskogen","Söderskogen","Vibyäng"],
"Torsby kommun":["Oleby","Stöllet","Sysslebäck","Torsby"],
"Härryda kommun":["Eskilsby och Snugga","Hindås","Hällingsjö","Härryda","Landvetter","Mölnlycke","Nya Långenäs","Rya","Rävlanda","Stora Bugärde"],
"Valdemarsviks kommun":["Gryt","Gusum","Ringarum","Valdemarsvik"],
"Trosa kommun":["Sund","Trosa","Vagnhärad","Västerljung","Öbolandet"],
"Norsjö kommun":["Bastuträsk","Norsjö"],
"Öckerö kommun":["Björkö","Fotö","Hälsö","Hönö","Kalvsund","Källö-Knippla","Rörö","Öckerö"],
"Piteå kommun":["Bergsviken","Blåsmark","Böle","Hemmingsmark","Hortlax","Jävre","Kopparnäs","Lillpite","Norrfjärden","Piteå","Roknäs","Rosvik","Sjulsmark","Svartudden","Svensbyn"],
"Munkedals kommun":["Dingle","Hedekas","Hällevadsholm","Munkedal","Torreby"],
"Göteborgs kommun":["Angered","Asperö","Björlanda och Torslanda","Brännö","Donsö","Göteborg","Helgered","Nolvik","Nordöstra Göteborg","Olofstorp","Stenared","Styrsö","Säve","Tumlehed","Vrångö"],
"Gnesta kommun":["Björnlunda","Gnesta","Stjärnhov"],
"Hjo kommun":["Hjo","Korsberga"],
"Forshaga kommun":["Deje","Dyvelsten","Forshaga"],
"Härnösands kommun":["Härnösand","Ramvik","Älandsbro"],
"Lessebo kommun":["Hovmantorp","Kosta","Lessebo","Skruv"],
"Laxå kommun":["Finnerödja","Hasselfors","Laxå"],
"Ydre kommun":["Hestra","Rydsnäs","Österbymo"],
"Bjuvs kommun":["Bjuv","Ekeby"],
"Huddinge kommun":["Gladö kvarn","Vidja","Östorp och Ådran"],
"Västerviks kommun":["Ankarsrum","Edsbruk","Gamleby","Gunnebo","Hjorted","Loftahammar","Piperskärr","Totebo","Västervik","Överum"],
"Dals-Eds kommun":["Ed"],
"Strömsunds kommun":["Backe","Gäddede","Hammerdal","Hoting","Näsviken","Rossön","Strömsund"],
"Avesta kommun":["Avesta","Folkärna","Fors","Horndal","Krylbo","Nordanö","Näs bruk"],
"Helsingborgs kommun":["Allerum","Bårslöv","Domsten","Fleninge","Gantofta","Hasslarp","Helsingborg","Hittarp","Kattarp","Mörarp","Påarp","Rydebäck","Tånga och Rögle","Utvälinge","Vallåkra","Ödåkra"],
"Alingsås kommun":["Alingsås","Färgens östra strand","Gräfsnäs","Hemsjö","Hjälmared","Ingared","Långared","Magra","Ryd","Sollebrunn","Stora Mellby","Västerbodarna"],
"Timrå kommun":["Bergeforsen","Laggarberg","Stavreviken","Söråker","Timrå"],
"Uddevalla kommun":["Ammenäs","Fagerhult","Hogstorp","Kristevik och Sundsandsvik","Kurveröd","Lanesund och Överby","Ljungskile","Sjöskogen och Strand","Smedseröd","Strandskogen, Restenäs och Ulvesund","Uddevalla","Utby"],
"Oskarshamns kommun":["Bockara","Emsfors","Figeholm","Fårbo","Kristdala","Oskarshamn","Påskallavik"],
"Sollefteå kommun":["Junsele","Långsele","Näsåker","Ramsele","Sollefteå","Sollefteå norra"],
"Vaggeryds kommun":["Bondstorp","Hok","Klevshult","Skillingaryd","Vaggeryd"],
"Norbergs kommun":["Norberg"],
"Båstads kommun":["Båstad","Förslöv","Grevie","Torekov","Västra Karup","Östra Karup"],
"Kristianstads kommun":["Arkelstorp","Balsby","Bjärlöv","Bäckaskog","Degeberga","Everöd","Fjälkinge","Färlöv","Gärds Köpinge","Hammar","Hammarslund","Huaröd","Kristianstad","Linderöd","Nyehusen","Rinkaby","Tollarp","Vinnö","Vittskövle","Vånga","Yngsjö","Åhus","Önnestad","Österslöv","Östra Sönnarslöv"],
"Östhammars kommun":["Alunda","Dannemora","Gimo","Hargshamn","Skoby","Öregrund","Österbybruk","Östhammar"],
"Ludvika kommun":["Blötberget","Fredriksberg västra","Fredriksberg östra","Gonäs","Grängesberg","Grängesberg västra","Håksberg","Ludvika","Norrbo och Västansjö","Nyhammar","Sandudden och Hörks hage","Saxdalen","Sunnansjö","Sörvik"],
"Boxholms kommun":["Boxholm","Strålsnäs"],
"Oxelösunds kommun":["Inskogen","Oxelösund"],
"Alvesta kommun":["Alvesta","Grimslöv","Hjortsberga","Moheda","Torpsbruk","Vislanda"],
"Lerums kommun":["Björboholm","Gråbo","Lerum","Sjövik","Slätthult","Tollered","Öxeryd"],
"Falköpings kommun":["Falköping","Floby","Gudhem","Kinnarp","Kättilstorp","Odensberg","Stenstorp","Torbjörntorp","Vartofta","Åsarp"],
"Motala kommun":["Borensberg","Fornåsa","Fågelsta","Klockrike","Motala","Nykyrka","Tjällmo","Västanvik","Österstad"],
"Tanums kommun":["Fjällbacka","Grebbestad","Hamburgsund","Rabbalshede","Tanumshede"],
"Mölndals kommun":["Hällesåker"],
"Jokkmokks kommun":["Jokkmokk","Porjus","Vuollerim"],
"Örkelljunga kommun":["Eket","Skånes-Fagerhult","Åsljunga","Örkelljunga"],
"Kiruna kommun":["Jukkasjärvi","Karesuando","Kiruna","Kuttainen","Svappavaara","Tuolluvaara","Vittangi"],
"Borås kommun":["Aplared","Borgstena","Borås","Bosnäs","Bredared","Dalsjöfors","Dannike","Fristad","Gånghester","Hedared","Kinnarumma","Rydboholm","Rångedala","Sandared","Sandhult","Viskafors","Äspered"],
"Malå kommun":["Malå"],
"Bengtsfors kommun":["Bengtsfors","Billingsfors","Bäckefors","Dals Långed","Skåpafors"],
"Karlshamns kommun":["Hällaryd","Karlshamn","Mörrum","Stilleryd","Svängsta","Åryd"],
"Hörby kommun":["Hörby","Osbyholm","Önneköp"],
"Bollebygds kommun":["Bollebygd","Hultafors","Olsfors","Töllsjö"],
"Kungsörs kommun":["Kungsör","Valskog"],
"Tidaholms kommun":["Ekedalen","Madängsholm","Tidaholm"],
"Askersunds kommun":["Askersund","Hammar","Olshammar","Rönneshytta","Zinkgruvan","Åmmeberg","Åsbro"],
"Bräcke kommun":["Bräcke","Gällö","Kälarne","Pilgrimstad"],
"Knivsta kommun":["Alsike","Knivsta","Edeby"],
"Lindesbergs kommun":["Fellingsbro","Frövi","Gusselby","Lindesberg","Ramsberg","Rockhammar","Storå","Stråssa","Vedevåg"],
"Vingåkers kommun":["Baggetorp","Högsjö","Läppe","Marmorbyn","Vingåker"],
"Värnamo kommun":["Bor","Bredaryd","Forsheda","Horda","Hånger","Kärda","Lanna","Rydaholm","Tånnö","Värnamo","Åminne"],
"Borgholms kommun":["Borgholm","Löttorp","Rälla","Stora Rör"],
"Kalix kommun":["Bredviken","Båtskärsnäs","Gammelgården","Kalix","Nyborg","Påläng","Risögrund","Rolfs","Sangis","Töre"],
"Orust kommun":["Ellös","Henån","Höggeröd","Mollösund","Svanesund","Varekil","Vindön"],
"Gällivare kommun":["Gällivare","Hakkas","Koskullskulle","Malmberget västra","Malmberget östra","Tjautjas"],
"Hässleholms kommun":["Ballingslöv","Bjärnum","Emmaljunga","Finja","Hässleholm","Hästveda","Hörja","Mala","Röke","Sjörröd","Stoby","Sösdala","Tormestorp","Tyringe","Vankiva","Vinslöv","Vittsjö"],
"Norrköpings kommun":["Berga","Djurön","Eksund","Graversfors","Herstadberg","Kimstad","Krokek","Kvarsebo","Lindö","Ljunga","Marbystrand","Norrköping","Norsholm","Simonstorp","Skärblacka","Svärtinge","Åby","Öbonäs","Östra Husby"],
"Tierps kommun":["Karlholmsbruk","Mehedeby","Månkarbo","Skärplinge","Söderfors","Tierp","Tobo","Upplanda","Örbyhus"],
"Habo kommun":["Fagerhult","Furusjö","Habo","Rödån"],
"Ljusdals kommun":["Färila","Hybo","Järvsö","Lillhaga","Ljusdal","Los","Tallåsen"],
"Vindelns kommun":["Granö","Hällnäs","Tvärålund","Vindeln"],
"Strömstads kommun":["Kebal","Skee","Stare","Strömstad"],
"Markaryds kommun":["Markaryd","Strömsnäsbruk","Traryd"],
"Svedala kommun":["Bara","Holmeja","Klågerup","Svedala"],
"Laholms kommun":["Genevad","Hasslöv","Hishult","Knäred","Laholm","Lilla Tjärby","Mellbystrand","Ränneslöv","Skottorp","Vallberga","Veinge","Våxtorp","Ysby"],
"Bollnäs kommun":["Arbrå","Bollnäs","Freluga","Kilafors","Lottefors","Rengsjö","Segersta","Sibo","Vallsta"],
"Nynäshamns kommun":["Grödby","Landfjärden","Lidatorp och Klövsta","Nynäshamn","Oxnö och Svärdsö","Segersäng","Sorunda","Stora Vika","Ösmo"],
"Malung-Sälens kommun":["Limedsforsen","Malung","Malungsfors","Sälen","Transtrand"],
"Töreboda kommun":["Moholm","Töreboda","Älgarås"],
"Eslövs kommun":["Billinge","Eslöv","Flyinge","Gårdstånga","Harlösa","Hurva","Kungshult","Löberöd","Marieholm","Stehag","Stockamöllan","Väggarp","Örtofta"],
"Skurups kommun":["Abbekås","Rydsgård","Skivarp","Skurup"],
"Tibro kommun":["Fagersanna","Tibro"],
"Säters kommun":["Enbacka","Skedvi kyrkby","Solvarbo","Säter"],
"Dorotea kommun":["Dorotea"],
"Vårgårda kommun":["Horla","Vårgårda","Östadkulle"],
"Jönköpings kommun":["Bankeryd","Barnarp och Odensjö","Bottnaryd","Gissebo","Gränna","Jönköping","Kaxholmen","Kortebo","Lekeryd","Ryd","Skärstad","Taberg","Tenhult","Tunnerstad","Öggestorp","Ölmstad","Örserum"],
"Danderyds kommun":["Tranholmen"],
"Rättviks kommun":["Backa","Boda","Furudal","Gulleråsen","Nedre Gärdsjö","Rättvik","Vikarbyn"],
"Kungsbacka kommun":["Billdal","Buerås","Fjärås kyrkby","Fjärås station","Frillesås","Gundal och Högås","Hagryd-Dala","Halla Heberg","Hjälm","Kläppa","Onsala","Röda holme","Sätinge","Vallda","Västra Hagen","Åsa"],
"Lidköpings kommun":["Filsbäck","Järpås","Lidköping","Lidköping norra","Saleby","Vinninga","Örslösa"],
"Vara kommun":["Arentorp","Emtunga","Jung","Kvänum","Larv","Stora Levene","Tråvad","Vara","Vedum"],
"Vellinge kommun":["Arrie","Gessie Villastad","Hököpinge","Höllviken","Skanör med Falsterbo","Vellinge","Västra Ingelstad","Östra Grevie"],
"Krokoms kommun":["Aspås","Birka","Dvärsätt","Föllinge","Hissmofors","Krokom","Nälden","Trångsviken","Vaplan","Ås","Änge"],
"Hofors kommun":["Hofors","Robertsholm","Torsåker"],
"Landskrona kommun":["Annelöv","Asmundtorp","Glumslöv","Häljarp","Härslöv","Kvärlöv","Landskrona","Saxtorpsskogen","Tuna"],
"Aneby kommun":["Aneby","Frinnaryd","Sundhultsbrunn"],
"Vaxholms kommun":["Kullö","Resarö","Rindö","Skarpö","Tynningö","Vaxholm"],
"Uppsala kommun":["Almunge","Björklinge","Blackstalund","Bälinge","Bärby","Danmark","Funbo","Gunsta","Gåvsta","Håga","Jälla","Järlåsa","Knutby","Läby","Länna","Lövstalöt","Marielund och Selknä","Ramstalund","Skyttorp","Skölsta","Storvreta","Sävja","Ultuna","Uppsala","Vattholma","Vårdsätra","Vänge","Ytternäs och Vreta"],
"Tjörns kommun":["Bleket","Djupvik och Fagerfjäll","Höviksnäs","Klädesholmen","Klövedal","Kyrkesund","Kållekärr","Myggenäs","Rönnäng","Skärhamn","Stora Dyrön"],
"Lidingö kommun":["Lidingö","Sticklinge udde"],
"Karlstads kommun":["Alster","Blombacka","Edsgatan och Långenäs","Edsvalla","Edsvalla Övre bruket","Karlstad","Molkom","Norsbron","Råtorp","Skattkärr","Skåre","Vallargärdet","Vålberg","Väse"],
"Nordmalings kommun":["Lögdeå","Nordmaling","Rundvik"],
"Falkenbergs kommun":["Bergagård","Falkenberg","Fegen","Glommen","Heberg","Köinge","Långasand och Ugglarp","Långås","Morup","Skrea","Slöinge","Ullared","Vessigebro","Vinberg","Vinbergs kyrkby","Årstad","Älvsered","Ätran"],
"Vadstena kommun":["Vadstena"],
"Kungälvs kommun":["Arvidsvik","Aröd och Timmervik","Diseröd","Duvesjön","Kareby och Ringby","Kode","Kovikshamn","Kungälv","Kyrkeby och Nereby","Kärna","Lundby","Marstrand","Risby","Rishammar","Rörtången och Ödsmåls mosse","Signehög och Norrmannebo","Solberga","Tjuvkil","Ödsmål och Åsebyberg"],
"Lekebergs kommun":["Fjugesta","Gropen","Mullhyttan","Vintrosa"],
"Kumla kommun":["Ekeby","Kumla","Åbytorp"],
"Svalövs kommun":["Billeberga","Kågeröd","Röstånga","Svalöv","Teckomatorp","Tågarp"],
"Filipstads kommun":["Filipstad","Lesjöfors","Nykroppa","Persberg"],
"Kramfors kommun":["Bollstabruk","Docksta","Herrskog","Klockestrand","Kramfors","Lunde","Lugnvik","Mjällom","Nordingrå","Nyland","Sandslån","Ullånger"],
"Storumans kommun":["Hemavan","Stensele","Storuman","Tärnaby"],
"Skövde kommun":["Igelstorp","Lerdala","Skultorp","Skövde","Stöpen","Tidan","Timmersdala","Ulvåker","Väring","Värsås"],
"Mariestads kommun":["Lugnås","Lyrestad","Mariestad","Sjötorp","Ullervad"],
"Trollhättans kommun":["Sjuntorp","Trollhättan","Upphärad","Velanda","Väne-Åsaka"],
"Karlskrona kommun":["Drottningskär","Fridlevstad","Fågelmara","Gängletorp","Hasslö","Holmsjö","Jämjö","Karlskrona","Kättilsmåla","Nättraby","Nävragöl","Ramdala","Rödeby","Sjuhalla","Skavkulla och Skillingenäs","Spjutsbygd","Sturkö","Torhamn","Tving"],
"Surahammars kommun":["Ramnäs","Surahammar","Virsbo"],
"Kalmars kommun":["Drag","Dunö","Hagby","Halltorp","Kalmar","Lindsdal","Ljungbyholm","Läckeby","Påryd","Rinkabyholm","Rockneby","Smedby","Trekanten","Tvärskog","Vassmolösa","Åmunnen"],
"Nacka kommun":["Fisksätra","Hästhagen","Kil","Saltsjöbaden","Älgö"],
"Kils kommun":["Fagerås","Högboda","Kil","Stenåsen"],
"Nora kommun":["Gyttorp","Nora","Striberg","Ås/Åshyttan"],
"Uppvidinge kommun":["Alstermo","Lenhovda","Norrhult-Klavreström","Åseda","Älghult"]
}

import json

counties = {}
for lan, kommuner in lan_kommun.items():
    municipalities = {}
    for kommun in kommuner:
        try:
            municipalities.update({kommun: kommun_tatort[kommun]})
        except:
            pass
    counties[lan] = municipalities
print(counties)
with open('counties.json', 'w') as outfile:
    json.dump(counties, outfile)
