lan = ["Dalarnas län",
"Jämtlands län",
"Skåne län",
"Värmlands län",
"Västernorrlands län",
"Östergötlands län",
"Jönköpings län",
"Hallands län",
"Kalmar län",
"Västerbottens län",
"Norrbottens län",
"Södermanlands län",
"Gävleborgs län",
"Gotlands län",
"Kronobergs län",
"Blekinge län",
"Stockholms län",
"Uppsala län",
"Västmanlands län",
"Västra Götalands län",
"Örebro län"]
lan = ["Dalarna",
"Jämtland",
"Skåne",
"Värmland",
"Västernorrland",
"Östergötland",
"Jönköping",
"Halland",
"Kalmar",
"Västerbotten",
"Norrbotten",
"Södermanland",
"Gävleborg",
"Gotland",
"Kronoberg",
"Blekinge",
"Stockholm",
"Uppsala",
"Västmanland",
"Västra Götaland",
"Örebro"]
kommun_lan = [['Ale kommun', 'Västra Götalands län'],
['Alingsås kommun', 'Västra Götalands län'],
['Alvesta kommun', 'Kronobergs län'],
['Aneby kommun', 'Jönköpings län'],
['Arboga kommun', 'Västmanlands län'],
['Arjeplogs kommun', 'Norrbottens län'],
['Arvidsjaurs kommun', 'Norrbottens län'],
['Arvika kommun', 'Värmlands län'],
['Askersunds kommun', 'Örebro län'],
['Avesta kommun', 'Dalarnas län'],
['Bengtsfors kommun', 'Västra Götalands län'],
['Bergs kommun', 'Jämtlands län'],
['Bjurholms kommun', 'Västerbottens län'],
['Bjuvs kommun', 'Skåne län'],
['Bodens kommun', 'Norrbottens län'],
['Bollebygds kommun', 'Västra Götalands län'],
['Bollnäs kommun', 'Gävleborgs län'],
['Borgholms kommun', 'Kalmar län'],
['Borlänge kommun', 'Dalarnas län'],
['Borås kommun', 'Västra Götalands län'],
['Botkyrka kommun', 'Stockholms län'],
['Boxholms kommun', 'Östergötlands län'],
['Bromölla kommun', 'Skåne län'],
['Bräcke kommun', 'Jämtlands län'],
['Burlövs kommun', 'Skåne län'],
['Båstads kommun', 'Skåne län'],
['Dals-Eds kommun', 'Västra Götalands län'],
['Danderyds kommun', 'Stockholms län'],
['Degerfors kommun', 'Örebro län'],
['Dorotea kommun', 'Västerbottens län'],
['Eda kommun', 'Värmlands län'],
['Ekerö kommun', 'Stockholms län'],
['Eksjö kommun', 'Jönköpings län'],
['Emmaboda kommun', 'Kalmar län'],
['Enköpings kommun', 'Uppsala län'],
['Eskilstuna kommun', 'Södermanlands län'],
['Eslövs kommun', 'Skåne län'],
['Essunga kommun', 'Västra Götalands län'],
['Fagersta kommun', 'Västmanlands län'],
['Falkenbergs kommun', 'Hallands län'],
['Falköpings kommun', 'Västra Götalands län'],
['Falu kommun', 'Dalarnas län'],
['Filipstads kommun', 'Värmlands län'],
['Finspångs kommun', 'Östergötlands län'],
['Flens kommun', 'Södermanlands län'],
['Forshaga kommun', 'Värmlands län'],
['Färgelanda kommun', 'Västra Götalands län'],
['Gagnefs kommun', 'Dalarnas län'],
['Gislaveds kommun', 'Jönköpings län'],
['Gnesta kommun', 'Södermanlands län'],
['Gnosjö kommun', 'Jönköpings län'],
['Gotlands kommun', 'Gotlands län'],
['Grums kommun', 'Värmlands län'],
['Grästorps kommun', 'Västra Götalands län'],
['Gullspångs kommun', 'Västra Götalands län'],
['Gällivare kommun', 'Norrbottens län'],
['Gävle kommun', 'Gävleborgs län'],
['Göteborgs kommun', 'Västra Götalands län'],
['Götene kommun', 'Västra Götalands län'],
['Habo kommun', 'Jönköpings län'],
['Hagfors kommun', 'Värmlands län'],
['Hallsbergs kommun', 'Örebro län'],
['Hallstahammars kommun', 'Västmanlands län'],
['Halmstads kommun', 'Hallands län'],
['Hammarö kommun', 'Värmlands län'],
['Haninge kommun', 'Stockholms län'],
['Haparanda kommun', 'Norrbottens län'],
['Heby kommun', 'Uppsala län'],
['Hedemora kommun', 'Dalarnas län'],
['Helsingborgs kommun', 'Skåne län'],
['Herrljunga kommun', 'Västra Götalands län'],
['Hjo kommun', 'Västra Götalands län'],
['Hofors kommun', 'Gävleborgs län'],
['Huddinge kommun', 'Stockholms län'],
['Hudiksvalls kommun', 'Gävleborgs län'],
['Hultsfreds kommun', 'Kalmar län'],
['Hylte kommun', 'Hallands län'],
['Håbo kommun', 'Uppsala län'],
['Hällefors kommun', 'Örebro län'],
['Härjedalens kommun', 'Jämtlands län'],
['Härnösands kommun', 'Västernorrlands län'],
['Härryda kommun', 'Västra Götalands län'],
['Hässleholms kommun', 'Skåne län'],
['Höganäs kommun', 'Skåne län'],
['Högsby kommun', 'Kalmar län'],
['Hörby kommun', 'Skåne län'],
['Höörs kommun', 'Skåne län'],
['Jokkmokks kommun', 'Norrbottens län'],
['Järfälla kommun', 'Stockholms län'],
['Jönköpings kommun', 'Jönköpings län'],
['Kalix kommun', 'Norrbottens län'],
['Kalmar kommun', 'Kalmar län'],
['Karlsborgs kommun', 'Västra Götalands län'],
['Karlshamns kommun', 'Blekinge län'],
['Karlskoga kommun', 'Örebro län'],
['Karlskrona kommun', 'Blekinge län'],
['Karlstads kommun', 'Värmlands län'],
['Katrineholms kommun', 'Södermanlands län'],
['Kils kommun', 'Värmlands län'],
['Kinda kommun', 'Östergötlands län'],
['Kiruna kommun', 'Norrbottens län'],
['Klippans kommun', 'Skåne län'],
['Knivsta kommun', 'Uppsala län'],
['Kramfors kommun', 'Västernorrlands län'],
['Kristianstads kommun', 'Skåne län'],
['Kristinehamns kommun', 'Värmlands län'],
['Krokoms kommun', 'Jämtlands län'],
['Kumla kommun', 'Örebro län'],
['Kungsbacka kommun', 'Hallands län'],
['Kungsörs kommun', 'Västmanlands län'],
['Kungälvs kommun', 'Västra Götalands län'],
['Kävlinge kommun', 'Skåne län'],
['Köpings kommun', 'Västmanlands län'],
['Laholms kommun', 'Hallands län'],
['Landskrona kommun', 'Skåne län'],
['Laxå kommun', 'Örebro län'],
['Lekebergs kommun', 'Örebro län'],
['Leksands kommun', 'Dalarnas län'],
['Lerums kommun', 'Västra Götalands län'],
['Lessebo kommun', 'Kronobergs län'],
['Lidingö kommun', 'Stockholms län'],
['Lidköpings kommun', 'Västra Götalands län'],
['Lilla Edets kommun', 'Västra Götalands län'],
['Lindesbergs kommun', 'Örebro län'],
['Linköpings kommun', 'Östergötlands län'],
['Ljungby kommun', 'Kronobergs län'],
['Ljusdals kommun', 'Gävleborgs län'],
['Ljusnarsbergs kommun', 'Örebro län'],
['Lomma kommun', 'Skåne län'],
['Ludvika kommun', 'Dalarnas län'],
['Luleå kommun', 'Norrbottens län'],
['Lunds kommun', 'Skåne län'],
['Lycksele kommun', 'Västerbottens län'],
['Lysekils kommun', 'Västra Götalands län'],
['Malmö kommun', 'Skåne län'],
['Malung-Sälens kommun', 'Dalarnas län'],
['Malå kommun', 'Västerbottens län'],
['Mariestads kommun', 'Västra Götalands län'],
['Marks kommun', 'Västra Götalands län'],
['Markaryds kommun', 'Kronobergs län'],
['Melleruds kommun', 'Västra Götalands län'],
['Mjölby kommun', 'Östergötlands län'],
['Mora kommun', 'Dalarnas län'],
['Motala kommun', 'Östergötlands län'],
['Mullsjö kommun', 'Jönköpings län'],
['Munkedals kommun', 'Västra Götalands län'],
['Munkfors kommun', 'Värmlands län'],
['Mölndals kommun', 'Västra Götalands län'],
['Mönsterås kommun', 'Kalmar län'],
['Mörbylånga kommun', 'Kalmar län'],
['Nacka kommun', 'Stockholms län'],
['Nora kommun', 'Örebro län'],
['Norbergs kommun', 'Västmanlands län'],
['Nordanstigs kommun', 'Gävleborgs län'],
['Nordmalings kommun', 'Västerbottens län'],
['Norrköpings kommun', 'Östergötlands län'],
['Norrtälje kommun', 'Stockholms län'],
['Norsjö kommun', 'Västerbottens län'],
['Nybro kommun', 'Kalmar län'],
['Nykvarns kommun', 'Stockholms län'],
['Nyköpings kommun', 'Södermanlands län'],
['Nynäshamns kommun', 'Stockholms län'],
['Nässjö kommun', 'Jönköpings län'],
['Ockelbo kommun', 'Gävleborgs län'],
['Olofströms kommun', 'Blekinge län'],
['Orsa kommun', 'Dalarnas län'],
['Orusts kommun', 'Västra Götalands län'],
['Osby kommun', 'Skåne län'],
['Oskarshamns kommun', 'Kalmar län'],
['Ovanåkers kommun', 'Gävleborgs län'],
['Oxelösunds kommun', 'Södermanlands län'],
['Pajala kommun', 'Norrbottens län'],
['Partille kommun', 'Västra Götalands län'],
['Perstorps kommun', 'Skåne län'],
['Piteå kommun', 'Norrbottens län'],
['Ragunda kommun', 'Jämtlands län'],
['Robertsfors kommun', 'Västerbottens län'],
['Ronneby kommun', 'Blekinge län'],
['Rättviks kommun', 'Dalarnas län'],
['Sala kommun', 'Västmanlands län'],
['Salems kommun', 'Stockholms län'],
['Sandvikens kommun', 'Gävleborgs län'],
['Sigtuna kommun', 'Stockholms län'],
['Simrishamns kommun', 'Skåne län'],
['Sjöbo kommun', 'Skåne län'],
['Skara kommun', 'Västra Götalands län'],
['Skellefteå kommun', 'Västerbottens län'],
['Skinnskattebergs kommun', 'Västmanlands län'],
['Skurups kommun', 'Skåne län'],
['Skövde kommun', 'Västra Götalands län'],
['Smedjebackens kommun', 'Dalarnas län'],
['Sollefteå kommun', 'Västernorrlands län'],
['Sollentuna kommun', 'Stockholms län'],
['Solna kommun', 'Stockholms län'],
['Sorsele kommun', 'Västerbottens län'],
['Sotenäs kommun', 'Västra Götalands län'],
['Staffanstorps kommun', 'Skåne län'],
['Stenungsunds kommun', 'Västra Götalands län'],
['Stockholms kommun', 'Stockholms län'],
['Storfors kommun', 'Värmlands län'],
['Storumans kommun', 'Västerbottens län'],
['Strängnäs kommun', 'Södermanlands län'],
['Strömstads kommun', 'Västra Götalands län'],
['Strömsunds kommun', 'Jämtlands län'],
['Sundbybergs kommun', 'Stockholms län'],
['Sundsvalls kommun', 'Västernorrlands län'],
['Sunne kommun', 'Värmlands län'],
['Surahammars kommun', 'Västmanlands län'],
['Svalövs kommun', 'Skåne län'],
['Svedala kommun', 'Skåne län'],
['Svenljunga kommun', 'Västra Götalands län'],
['Säffle kommun', 'Värmlands län'],
['Säters kommun', 'Dalarnas län'],
['Sävsjö kommun', 'Jönköpings län'],
['Söderhamns kommun', 'Gävleborgs län'],
['Söderköpings kommun', 'Östergötlands län'],
['Södertälje kommun', 'Stockholms län'],
['Sölvesborgs kommun', 'Blekinge län'],
['Tanums kommun', 'Västra Götalands län'],
['Tibro kommun', 'Västra Götalands län'],
['Tidaholms kommun', 'Västra Götalands län'],
['Tierps kommun', 'Uppsala län'],
['Timrå kommun', 'Västernorrlands län'],
['Tingsryds kommun', 'Kronobergs län'],
['Tjörns kommun', 'Västra Götalands län'],
['Tomelilla kommun', 'Skåne län'],
['Torsby kommun', 'Värmlands län'],
['Torsås kommun', 'Kalmar län'],
['Tranemo kommun', 'Västra Götalands län'],
['Tranås kommun', 'Jönköpings län'],
['Trelleborgs kommun', 'Skåne län'],
['Trollhättans kommun', 'Västra Götalands län'],
['Trosa kommun', 'Södermanlands län'],
['Tyresö kommun', 'Stockholms län'],
['Täby kommun', 'Stockholms län'],
['Töreboda kommun', 'Västra Götalands län'],
['Uddevalla kommun', 'Västra Götalands län'],
['Ulricehamns kommun', 'Västra Götalands län'],
['Umeå kommun', 'Västerbottens län'],
['Upplands Väsby kommun', 'Stockholms län'],
['Upplands-Bro kommun', 'Stockholms län'],
['Uppsala kommun', 'Uppsala län'],
['Uppvidinge kommun', 'Kronobergs län'],
['Vadstena kommun', 'Östergötlands län'],
['Vaggeryds kommun', 'Jönköpings län'],
['Valdemarsviks kommun', 'Östergötlands län'],
['Vallentuna kommun', 'Stockholms län'],
['Vansbro kommun', 'Dalarnas län'],
['Vara kommun', 'Västra Götalands län'],
['Varbergs kommun', 'Hallands län'],
['Vaxholms kommun', 'Stockholms län'],
['Vellinge kommun', 'Skåne län'],
['Vetlanda kommun', 'Jönköpings län'],
['Vilhelmina kommun', 'Västerbottens län'],
['Vimmerby kommun', 'Kalmar län'],
['Vindelns kommun', 'Västerbottens län'],
['Vingåkers kommun', 'Södermanlands län'],
['Vårgårda kommun', 'Västra Götalands län'],
['Vänersborgs kommun', 'Västra Götalands län'],
['Vännäs kommun', 'Västerbottens län'],
['Värmdö kommun', 'Stockholms län'],
['Värnamo kommun', 'Jönköpings län'],
['Västerviks kommun', 'Kalmar län'],
['Västerås kommun', 'Västmanlands län'],
['Växjö kommun', 'Kronobergs län'],
['Ydre kommun', 'Östergötlands län'],
['Ystads kommun', 'Skåne län'],
['Åmåls kommun', 'Västra Götalands län'],
['Ånge kommun', 'Västernorrlands län'],
['Åre kommun', 'Jämtlands län'],
['Årjängs kommun', 'Värmlands län'],
['Åsele kommun', 'Västerbottens län'],
['Åstorps kommun', 'Skåne län'],
['Åtvidabergs kommun', 'Östergötlands län'],
['Älmhults kommun', 'Kronobergs län'],
['Älvdalens kommun', 'Dalarnas län'],
['Älvkarleby kommun', 'Uppsala län'],
['Älvsbyns kommun', 'Norrbottens län'],
['Ängelholms kommun', 'Skåne län'],
['Öckerö kommun', 'Västra Götalands län'],
['Ödeshögs kommun', 'Östergötlands län'],
['Örebro kommun', 'Örebro län'],
['Örkelljunga kommun', 'Skåne län'],
['Örnsköldsviks kommun', 'Västernorrlands län'],
['Östersunds kommun', 'Jämtlands län'],
['Österåkers kommun', 'Stockholms län'],
['Östhammars kommun', 'Uppsala län'],
['Östra Göinge kommun', 'Skåne län'],
['Överkalix kommun', 'Norrbottens län'],
['Övertorneå kommun', 'Norrbottens län']]
kommun_lan = [['Ale kommun', 'Västra Götaland'],
['Alingsås kommun', 'Västra Götaland'],
['Alvesta kommun', 'Kronoberg'],
['Aneby kommun', 'Jönköping'],
['Arboga kommun', 'Västmanland'],
['Arjeplogs kommun', 'Norrbotten'],
['Arvidsjaurs kommun', 'Norrbotten'],
['Arvika kommun', 'Värmland'],
['Askersunds kommun', 'Örebro'],
['Avesta kommun', 'Dalarna'],
['Bengtsfors kommun', 'Västra Götaland'],
['Bergs kommun', 'Jämtland'],
['Bjurholms kommun', 'Västerbotten'],
['Bjuvs kommun', 'Skåne'],
['Bodens kommun', 'Norrbotten'],
['Bollebygds kommun', 'Västra Götaland'],
['Bollnäs kommun', 'Gävleborg'],
['Borgholms kommun', 'Kalmar'],
['Borlänge kommun', 'Dalarna'],
['Borås kommun', 'Västra Götaland'],
['Botkyrka kommun', 'Stockholm'],
['Boxholms kommun', 'Östergötland'],
['Bromölla kommun', 'Skåne'],
['Bräcke kommun', 'Jämtland'],
['Burlövs kommun', 'Skåne'],
['Båstads kommun', 'Skåne'],
['Dals-Eds kommun', 'Västra Götaland'],
['Danderyds kommun', 'Stockholm'],
['Degerfors kommun', 'Örebro'],
['Dorotea kommun', 'Västerbotten'],
['Eda kommun', 'Värmland'],
['Ekerö kommun', 'Stockholm'],
['Eksjö kommun', 'Jönköping'],
['Emmaboda kommun', 'Kalmar'],
['Enköpings kommun', 'Uppsala'],
['Eskilstuna kommun', 'Södermanland'],
['Eslövs kommun', 'Skåne'],
['Essunga kommun', 'Västra Götaland'],
['Fagersta kommun', 'Västmanland'],
['Falkenbergs kommun', 'Halland'],
['Falköpings kommun', 'Västra Götaland'],
['Falu kommun', 'Dalarna'],
['Filipstads kommun', 'Värmland'],
['Finspångs kommun', 'Östergötland'],
['Flens kommun', 'Södermanland'],
['Forshaga kommun', 'Värmland'],
['Färgelanda kommun', 'Västra Götaland'],
['Gagnefs kommun', 'Dalarna'],
['Gislaveds kommun', 'Jönköping'],
['Gnesta kommun', 'Södermanland'],
['Gnosjö kommun', 'Jönköping'],
['Gotlands kommun', 'Gotland'],
['Grums kommun', 'Värmland'],
['Grästorps kommun', 'Västra Götaland'],
['Gullspångs kommun', 'Västra Götaland'],
['Gällivare kommun', 'Norrbotten'],
['Gävle kommun', 'Gävleborg'],
['Göteborgs kommun', 'Västra Götaland'],
['Götene kommun', 'Västra Götaland'],
['Habo kommun', 'Jönköping'],
['Hagfors kommun', 'Värmland'],
['Hallsbergs kommun', 'Örebro'],
['Hallstahammars kommun', 'Västmanland'],
['Halmstads kommun', 'Halland'],
['Hammarö kommun', 'Värmland'],
['Haninge kommun', 'Stockholm'],
['Haparanda kommun', 'Norrbotten'],
['Heby kommun', 'Uppsala'],
['Hedemora kommun', 'Dalarna'],
['Helsingborgs kommun', 'Skåne'],
['Herrljunga kommun', 'Västra Götaland'],
['Hjo kommun', 'Västra Götaland'],
['Hofors kommun', 'Gävleborg'],
['Huddinge kommun', 'Stockholm'],
['Hudiksvalls kommun', 'Gävleborg'],
['Hultsfreds kommun', 'Kalmar'],
['Hylte kommun', 'Halland'],
['Håbo kommun', 'Uppsala'],
['Hällefors kommun', 'Örebro'],
['Härjedalens kommun', 'Jämtland'],
['Härnösands kommun', 'Västernorrland'],
['Härryda kommun', 'Västra Götaland'],
['Hässleholms kommun', 'Skåne'],
['Höganäs kommun', 'Skåne'],
['Högsby kommun', 'Kalmar'],
['Hörby kommun', 'Skåne'],
['Höörs kommun', 'Skåne'],
['Jokkmokks kommun', 'Norrbotten'],
['Järfälla kommun', 'Stockholm'],
['Jönköpings kommun', 'Jönköping'],
['Kalix kommun', 'Norrbotten'],
['Kalmar kommun', 'Kalmar'],
['Karlsborgs kommun', 'Västra Götaland'],
['Karlshamns kommun', 'Blekinge'],
['Karlskoga kommun', 'Örebro'],
['Karlskrona kommun', 'Blekinge'],
['Karlstads kommun', 'Värmland'],
['Katrineholms kommun', 'Södermanland'],
['Kils kommun', 'Värmland'],
['Kinda kommun', 'Östergötland'],
['Kiruna kommun', 'Norrbotten'],
['Klippans kommun', 'Skåne'],
['Knivsta kommun', 'Uppsala'],
['Kramfors kommun', 'Västernorrland'],
['Kristianstads kommun', 'Skåne'],
['Kristinehamns kommun', 'Värmland'],
['Krokoms kommun', 'Jämtland'],
['Kumla kommun', 'Örebro'],
['Kungsbacka kommun', 'Halland'],
['Kungsörs kommun', 'Västmanland'],
['Kungälvs kommun', 'Västra Götaland'],
['Kävlinge kommun', 'Skåne'],
['Köpings kommun', 'Västmanland'],
['Laholms kommun', 'Halland'],
['Landskrona kommun', 'Skåne'],
['Laxå kommun', 'Örebro'],
['Lekebergs kommun', 'Örebro'],
['Leksands kommun', 'Dalarna'],
['Lerums kommun', 'Västra Götaland'],
['Lessebo kommun', 'Kronoberg'],
['Lidingö kommun', 'Stockholm'],
['Lidköpings kommun', 'Västra Götaland'],
['Lilla Edets kommun', 'Västra Götaland'],
['Lindesbergs kommun', 'Örebro'],
['Linköpings kommun', 'Östergötland'],
['Ljungby kommun', 'Kronoberg'],
['Ljusdals kommun', 'Gävleborg'],
['Ljusnarsbergs kommun', 'Örebro'],
['Lomma kommun', 'Skåne'],
['Ludvika kommun', 'Dalarna'],
['Luleå kommun', 'Norrbotten'],
['Lunds kommun', 'Skåne'],
['Lycksele kommun', 'Västerbotten'],
['Lysekils kommun', 'Västra Götaland'],
['Malmö kommun', 'Skåne'],
['Malung-Sälens kommun', 'Dalarna'],
['Malå kommun', 'Västerbotten'],
['Mariestads kommun', 'Västra Götaland'],
['Marks kommun', 'Västra Götaland'],
['Markaryds kommun', 'Kronoberg'],
['Melleruds kommun', 'Västra Götaland'],
['Mjölby kommun', 'Östergötland'],
['Mora kommun', 'Dalarna'],
['Motala kommun', 'Östergötland'],
['Mullsjö kommun', 'Jönköping'],
['Munkedals kommun', 'Västra Götaland'],
['Munkfors kommun', 'Värmland'],
['Mölndals kommun', 'Västra Götaland'],
['Mönsterås kommun', 'Kalmar'],
['Mörbylånga kommun', 'Kalmar'],
['Nacka kommun', 'Stockholm'],
['Nora kommun', 'Örebro'],
['Norbergs kommun', 'Västmanland'],
['Nordanstigs kommun', 'Gävleborg'],
['Nordmalings kommun', 'Västerbotten'],
['Norrköpings kommun', 'Östergötland'],
['Norrtälje kommun', 'Stockholm'],
['Norsjö kommun', 'Västerbotten'],
['Nybro kommun', 'Kalmar'],
['Nykvarns kommun', 'Stockholm'],
['Nyköpings kommun', 'Södermanland'],
['Nynäshamns kommun', 'Stockholm'],
['Nässjö kommun', 'Jönköping'],
['Ockelbo kommun', 'Gävleborg'],
['Olofströms kommun', 'Blekinge'],
['Orsa kommun', 'Dalarna'],
['Orusts kommun', 'Västra Götaland'],
['Osby kommun', 'Skåne'],
['Oskarshamns kommun', 'Kalmar'],
['Ovanåkers kommun', 'Gävleborg'],
['Oxelösunds kommun', 'Södermanland'],
['Pajala kommun', 'Norrbotten'],
['Partille kommun', 'Västra Götaland'],
['Perstorps kommun', 'Skåne'],
['Piteå kommun', 'Norrbotten'],
['Ragunda kommun', 'Jämtland'],
['Robertsfors kommun', 'Västerbotten'],
['Ronneby kommun', 'Blekinge'],
['Rättviks kommun', 'Dalarna'],
['Sala kommun', 'Västmanland'],
['Salems kommun', 'Stockholm'],
['Sandvikens kommun', 'Gävleborg'],
['Sigtuna kommun', 'Stockholm'],
['Simrishamns kommun', 'Skåne'],
['Sjöbo kommun', 'Skåne'],
['Skara kommun', 'Västra Götaland'],
['Skellefteå kommun', 'Västerbotten'],
['Skinnskattebergs kommun', 'Västmanland'],
['Skurups kommun', 'Skåne'],
['Skövde kommun', 'Västra Götaland'],
['Smedjebackens kommun', 'Dalarna'],
['Sollefteå kommun', 'Västernorrland'],
['Sollentuna kommun', 'Stockholm'],
['Solna kommun', 'Stockholm'],
['Sorsele kommun', 'Västerbotten'],
['Sotenäs kommun', 'Västra Götaland'],
['Staffanstorps kommun', 'Skåne'],
['Stenungsunds kommun', 'Västra Götaland'],
['Stockholms kommun', 'Stockholm'],
['Storfors kommun', 'Värmland'],
['Storumans kommun', 'Västerbotten'],
['Strängnäs kommun', 'Södermanland'],
['Strömstads kommun', 'Västra Götaland'],
['Strömsunds kommun', 'Jämtland'],
['Sundbybergs kommun', 'Stockholm'],
['Sundsvalls kommun', 'Västernorrland'],
['Sunne kommun', 'Värmland'],
['Surahammars kommun', 'Västmanland'],
['Svalövs kommun', 'Skåne'],
['Svedala kommun', 'Skåne'],
['Svenljunga kommun', 'Västra Götaland'],
['Säffle kommun', 'Värmland'],
['Säters kommun', 'Dalarna'],
['Sävsjö kommun', 'Jönköping'],
['Söderhamns kommun', 'Gävleborg'],
['Söderköpings kommun', 'Östergötland'],
['Södertälje kommun', 'Stockholm'],
['Sölvesborgs kommun', 'Blekinge'],
['Tanums kommun', 'Västra Götaland'],
['Tibro kommun', 'Västra Götaland'],
['Tidaholms kommun', 'Västra Götaland'],
['Tierps kommun', 'Uppsala'],
['Timrå kommun', 'Västernorrland'],
['Tingsryds kommun', 'Kronoberg'],
['Tjörns kommun', 'Västra Götaland'],
['Tomelilla kommun', 'Skåne'],
['Torsby kommun', 'Värmland'],
['Torsås kommun', 'Kalmar'],
['Tranemo kommun', 'Västra Götaland'],
['Tranås kommun', 'Jönköping'],
['Trelleborgs kommun', 'Skåne'],
['Trollhättans kommun', 'Västra Götaland'],
['Trosa kommun', 'Södermanland'],
['Tyresö kommun', 'Stockholm'],
['Täby kommun', 'Stockholm'],
['Töreboda kommun', 'Västra Götaland'],
['Uddevalla kommun', 'Västra Götaland'],
['Ulricehamns kommun', 'Västra Götaland'],
['Umeå kommun', 'Västerbotten'],
['Upplands Väsby kommun', 'Stockholm'],
['Upplands-Bro kommun', 'Stockholm'],
['Uppsala kommun', 'Uppsala'],
['Uppvidinge kommun', 'Kronoberg'],
['Vadstena kommun', 'Östergötland'],
['Vaggeryds kommun', 'Jönköping'],
['Valdemarsviks kommun', 'Östergötland'],
['Vallentuna kommun', 'Stockholm'],
['Vansbro kommun', 'Dalarna'],
['Vara kommun', 'Västra Götaland'],
['Varbergs kommun', 'Halland'],
['Vaxholms kommun', 'Stockholm'],
['Vellinge kommun', 'Skåne'],
['Vetlanda kommun', 'Jönköping'],
['Vilhelmina kommun', 'Västerbotten'],
['Vimmerby kommun', 'Kalmar'],
['Vindelns kommun', 'Västerbotten'],
['Vingåkers kommun', 'Södermanland'],
['Vårgårda kommun', 'Västra Götaland'],
['Vänersborgs kommun', 'Västra Götaland'],
['Vännäs kommun', 'Västerbotten'],
['Värmdö kommun', 'Stockholm'],
['Värnamo kommun', 'Jönköping'],
['Västerviks kommun', 'Kalmar'],
['Västerås kommun', 'Västmanland'],
['Växjö kommun', 'Kronoberg'],
['Ydre kommun', 'Östergötland'],
['Ystads kommun', 'Skåne'],
['Åmåls kommun', 'Västra Götaland'],
['Ånge kommun', 'Västernorrland'],
['Åre kommun', 'Jämtland'],
['Årjängs kommun', 'Värmland'],
['Åsele kommun', 'Västerbotten'],
['Åstorps kommun', 'Skåne'],
['Åtvidabergs kommun', 'Östergötland'],
['Älmhults kommun', 'Kronoberg'],
['Älvdalens kommun', 'Dalarna'],
['Älvkarleby kommun', 'Uppsala'],
['Älvsbyns kommun', 'Norrbotten'],
['Ängelholms kommun', 'Skåne'],
['Öckerö kommun', 'Västra Götaland'],
['Ödeshögs kommun', 'Östergötland'],
['Örebro kommun', 'Örebro'],
['Örkelljunga kommun', 'Skåne'],
['Örnsköldsviks kommun', 'Västernorrland'],
['Östersunds kommun', 'Jämtland'],
['Österåkers kommun', 'Stockholm'],
['Östhammars kommun', 'Uppsala'],
['Östra Göinge kommun', 'Skåne'],
['Överkalix kommun', 'Norrbotten'],
['Övertorneå kommun', 'Norrbotten']]
lan_kommun = {"Dalarna":["Avesta kommun","Borlänge kommun","Falu kommun","Gagnefs kommun","Hedemora kommun","Leksands kommun","Ludvika kommun","Malung-Sälens kommun","Mora kommun","Orsa kommun","Rättviks kommun","Smedjebackens kommun","Säters kommun","Vansbro kommun","Älvdalens kommun"],
"Jämtland":["Bergs kommun","Bräcke kommun","Härjedalens kommun","Krokoms kommun","Ragunda kommun","Strömsunds kommun","Åre kommun","Östersunds kommun"],
"Skåne":["Bjuvs kommun","Bromölla kommun","Burlövs kommun","Båstads kommun","Eslövs kommun","Helsingborgs kommun","Hässleholms kommun","Höganäs kommun","Hörby kommun","Höörs kommun","Klippans kommun","Kristianstads kommun","Kävlinge kommun","Landskrona kommun","Lomma kommun","Lunds kommun","Malmö kommun","Osby kommun","Perstorps kommun","Simrishamns kommun","Sjöbo kommun","Skurups kommun","Staffanstorps kommun","Svalövs kommun","Svedala kommun","Tomelilla kommun","Trelleborgs kommun","Vellinge kommun","Ystads kommun","Åstorps kommun","Ängelholms kommun","Örkelljunga kommun","Östra Göinge kommun"],
"Värmland":["Arvika kommun","Eda kommun","Filipstads kommun","Forshaga kommun","Grums kommun","Hagfors kommun","Hammarö kommun","Karlstads kommun","Kils kommun","Kristinehamns kommun","Munkfors kommun","Storfors kommun","Sunne kommun","Säffle kommun","Torsby kommun","Årjängs kommun"],
"Västernorrland":["Härnösands kommun","Kramfors kommun","Sollefteå kommun","Sundsvalls kommun","Timrå kommun","Ånge kommun","Örnsköldsviks kommun"],
"Östergötland":["Boxholms kommun","Finspångs kommun","Kinda kommun","Linköpings kommun","Mjölby kommun","Motala kommun","Norrköpings kommun","Söderköpings kommun","Vadstena kommun","Valdemarsviks kommun","Ydre kommun","Åtvidabergs kommun","Ödeshögs kommun"],
"Jönköping":["Aneby kommun","Eksjö kommun","Gislaveds kommun","Gnosjö kommun","Habo kommun","Jönköpings kommun","Mullsjö kommun","Nässjö kommun","Sävsjö kommun","Tranås kommun","Vaggeryds kommun","Vetlanda kommun","Värnamo kommun"],
"Halland":["Falkenbergs kommun","Halmstads kommun","Hylte kommun","Kungsbacka kommun","Laholms kommun","Varbergs kommun"],
"Kalmar":["Borgholms kommun","Emmaboda kommun","Hultsfreds kommun","Högsby kommun","Kalmar kommun","Mönsterås kommun","Mörbylånga kommun","Nybro kommun","Oskarshamns kommun","Torsås kommun","Vimmerby kommun","Västerviks kommun"],
"Västerbotten":["Bjurholms kommun","Dorotea kommun","Lycksele kommun","Malå kommun","Nordmalings kommun","Norsjö kommun","Robertsfors kommun","Skellefteå kommun","Sorsele kommun","Storumans kommun","Umeå kommun","Vilhelmina kommun","Vindelns kommun","Vännäs kommun","Åsele kommun"],
"Norrbotten":["Arjeplogs kommun","Arvidsjaurs kommun","Bodens kommun","Gällivare kommun","Haparanda kommun","Jokkmokks kommun","Kalix kommun","Kiruna kommun","Luleå kommun","Pajala kommun","Piteå kommun","Älvsbyns kommun","Överkalix kommun","Övertorneå kommun"],
"Södermanland":["Eskilstuna kommun","Flens kommun","Gnesta kommun","Katrineholms kommun","Nyköpings kommun","Oxelösunds kommun","Strängnäs kommun","Trosa kommun","Vingåkers kommun"],
"Gävleborg":["Bollnäs kommun","Gävle kommun","Hofors kommun","Hudiksvalls kommun","Ljusdals kommun","Nordanstigs kommun","Ockelbo kommun","Ovanåkers kommun","Sandvikens kommun","Söderhamns kommun"],
"Gotland":["Gotlands kommun"],
"Kronoberg":["Alvesta kommun","Lessebo kommun","Ljungby kommun","Markaryds kommun","Tingsryds kommun","Uppvidinge kommun","Växjö kommun","Älmhults kommun"],
"Blekinge":["Karlshamns kommun","Karlskrona kommun","Olofströms kommun","Ronneby kommun","Sölvesborgs kommun"],
"Stockholm":["Botkyrka kommun","Danderyds kommun","Ekerö kommun","Haninge kommun","Huddinge kommun","Järfälla kommun","Lidingö kommun","Nacka kommun","Norrtälje kommun","Nykvarns kommun","Nynäshamns kommun","Salems kommun","Sigtuna kommun","Sollentuna kommun","Solna kommun","Stockholms kommun","Sundbybergs kommun","Södertälje kommun","Tyresö kommun","Täby kommun","Upplands Väsby kommun","Upplands-Bro kommun","Vallentuna kommun","Vaxholms kommun","Värmdö kommun","Österåkers kommun"],
"Uppsala":["Enköpings kommun","Heby kommun","Håbo kommun","Knivsta kommun","Tierps kommun","Uppsala kommun","Älvkarleby kommun","Östhammars kommun"],
"Västmanland":["Arboga kommun","Fagersta kommun","Hallstahammars kommun","Kungsörs kommun","Köpings kommun","Norbergs kommun","Sala kommun","Skinnskattebergs kommun","Surahammars kommun","Västerås kommun"],
"Västra Götaland":["Ale kommun","Alingsås kommun","Bengtsfors kommun","Bollebygds kommun","Borås kommun","Dals-Eds kommun","Essunga kommun","Falköpings kommun","Färgelanda kommun","Grästorps kommun","Gullspångs kommun","Göteborgs kommun","Götene kommun","Herrljunga kommun","Hjo kommun","Härryda kommun","Karlsborgs kommun","Kungälvs kommun","Lerums kommun","Lidköpings kommun","Lilla Edets kommun","Lysekils kommun","Mariestads kommun","Marks kommun","Melleruds kommun","Munkedals kommun","Mölndals kommun","Orusts kommun","Partille kommun","Skara kommun","Skövde kommun","Sotenäs kommun","Stenungsunds kommun","Strömstads kommun","Svenljunga kommun","Tanums kommun","Tibro kommun","Tidaholms kommun","Tjörns kommun","Tranemo kommun","Trollhättans kommun","Töreboda kommun","Uddevalla kommun","Ulricehamns kommun","Vara kommun","Vårgårda kommun","Vänersborgs kommun","Åmåls kommun","Öckerö kommun"],
"Örebro":["Askersunds kommun","Degerfors kommun","Hallsbergs kommun","Hällefors kommun","Karlskoga kommun","Kumla kommun","Laxå kommun","Lekebergs kommun","Lindesbergs kommun","Ljusnarsbergs kommun","Nora kommun","Örebro kommun"]
}